version: '3.7'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    build: ./db
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb

networks:
  app-network:
    driver: bridge

